### ISSUE TITLE
click Button full Screen App Crash 

### ISSUE THREAD

**Issue by fckvania** [dsa28s/compose-video#2]

**Comment by dsa28s** [comment]
@fckvania Hello fckvania! Please provide crash stacktrace?

**Comment by fckvania** [comment]
fix

**Comment by itsallan** [comment]
please how did you fix this  because me am still getting the error, this what i find in my log cat java.lang.IllegalStateException: Activity must be resumed to enter picture-in-picture

at android.app.Activity.enterPictureInPictureMode(Activity.java:3000)

at io.sanghun.compose.video.pip.PictureInPictureKt.enterPIPMode(PictureInPicture.kt:48)

at io.sanghun.compose.video.VideoPlayerKt$VideoPlayerSurface$3$observer$1.onStateChanged$lambda$1(VideoPlayer.kt:322)

at io.sanghun.compose.video.VideoPlayerKt$VideoPlayerSurface$3$observer$1.$r8$lambda$0Be49fLIItV09V1cjKwnrnuG8qc(Unknown Source:0)

at io.sanghun.compose.video.VideoPlayerKt$VideoPlayerSurface$3$observer$1$$ExternalSyntheticLambda0.run(Unknown Source:8)

at android.os.Handler.handleCallback(Handler.java:959)

at android.os.Handler.dispatchMessage(Handler.java:100)

at android.os.Looper.loopOnce(Looper.java:232)

at android.os.Looper.loop(Looper.java:317)

at android.app.ActivityThread.main(ActivityThread.java:8501)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
